ACS_INIT_CONTROL = "AiControlSystem\InitializeAiControl.sqf";
ACS_GROUP_STATE_CHECK_DELAY = 2;
ACS_ASR_AI_ENABLED = true;
ACS_DEBUG = true;

ACS_CONST_WAYPOINT_PATROL_LIMITED = ["MOVE", "COLUMN", "SAFE", "LIMITED", "YELLOW", 0, ["true",""], [0,0,0]];
ACS_CONST_WAYPOINT_PATROL_NORMAL = ["MOVE", "COLUMN", "SAFE", "NORMAL", "YELLOW", 0, ["true",""], [0,0,0]];
ACS_CONST_WAYPOINT_PATROL_FAST = ["MOVE", "COLUMN", "SAFE", "FULL", "YELLOW", 0, ["true",""], [0,0,0]];

ACS_CONST_WAYPOINT_HELI_PATROL_LIMITED = ["MOVE", "COLUMN", "SAFE", "LIMITED", "YELLOW", 100, ["true",""], [0,0,0]];
ACS_CONST_WAYPOINT_HELI_PATROL_NORMAL = ["MOVE", "COLUMN", "SAFE", "NORMAL", "YELLOW", 100, ["true",""], [0,0,0]];
ACS_CONST_WAYPOINT_HELI_PATROL_FAST = ["MOVE", "COLUMN", "SAFE", "FULL", "YELLOW", 100, ["true",""], [0,0,0]];